[build]

  # directory to change to before build
base = "client/"
  # Contains HTML file that's deploy ready
publish = "public/"


# redirect rules for Netlify
[[redirects]]
    from = "/*"
    to = "index.html"
    status = 200
    force = true
  headers = {X-From = "Netlify"}

  
